### PR TITLE
Fix endless loop issue

### LINKED ISSUE #14: endless loop error, when eval string `COUNT <= 20 && COUNT > 10`
This expression creates endless loop, but should return error because of unknown symbol.

```go
scope := map[string]any{
    "COUNT": 15,
}
input := `COUNT <= 20 && COUNT > 10`
res, err := EvalStringWithScope(input, scope)
```

### PR DESCRIPTION
**Pull request by nitram509**
Hint: without the checks for error, the parser remains within an endless loop.
Thus, the fix is to check for error on each .Next() operation.

fix #14

### CODE REVIEW

File: temporal.go [hunk 1]
```diff
@@ -269,17 +269,17 @@ func (duration FEELDuration) MarshalJSON() ([]byte, error) {
 
 func (duration FEELDuration) Duration() time.Duration {
```
Comment (richardbizik) [inline temporal.go:270]: Correct me if I am wrong but we can calculate the time.Duration only when we know the date to which feel duration from iso 8601 applies to. And even then we should use functions AddDate and Add to calculate it correctly.

File: parser.go [hunk 2]
```diff
@@ -80,12 +80,18 @@ func (p Parser) CurrentToken() ScannerToken {
...
+		return nil, err
+	}
 	var exps []Node
 
 	for !p.CurrentToken().Expect(TokenEOF) {
 		if p.CurrentToken().Expect(";") {
-			p.scanner.Next()
+			err = p.scanner.Next()
+			if err != nil {
+				return nil, err
```
Comment (richardbizik) [inline parser.go:93]: I would add some more error details about what were we trying to parse to each `return nil, err`.

**Review by richardbizik — CHANGES_REQUESTED** [review]

File: temporal.go (hunk 1 above)
Comment (nitram509) [reply temporal.go:270]: Uugh, good question ... need to dig deeper on that.
Did create a ticket for that to be re-evaluated: https://github.com/pbinitiative/feel/issues/16
Prefer to tackle this separately.

File: parser.go (hunk 2 above)
Comment (nitram509) [reply parser.go:93]: Meaningful errors are created inside the `.Next()` call (including Line/Position numbers).
What kind of error details do you expect to see "on-top" ?

Comment (richardbizik) [reply parser.go:93]: Next() has only `at position %d %d, bad input %s` and `EOF`
I would expect something like `Expected comparison operator, got: EOF` since we are doing manual parsing we might as well take advantage of that and provide as much detail in errors as possible.

Comment (nitram509) [reply parser.go:93]: Got your point and created a new issue: https://github.com/pbinitiative/feel/issues/17
I prefer to focus this PR only on the fix ... improving error messages is IMHO a bigger task and should be tackled separately.

**Review by richardbizik — APPROVED** [review]
